artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/krishnaik06/datasets/raw/refs/heads/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samasum_dataset
  tokenizer_name: "google/pegasus-cnn_dailymail"
  train_path: "artifacts/data_ingestion/samsum-train.csv"
  val_path: "artifacts/data_ingestion/samsum-validation.csv"
  test_path: "artifacts/data_ingestion/samsum-test.csv"


data_trainer:
  root_dir: artifacts/data_trainer
  model_ckpt: "google/pegasus-cnn_dailymail"
  train_path: "artifacts/data_transformation/samsum-dataset/train"
  val_path: "artifacts/data_transformation/samsum-dataset/val"
  test_path: "artifacts/data_transformation/samsum-dataset/test"


